import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/navbar'
import Providers from '@/context/providers'

const roboto = Roboto({ weight: '400', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html id='dev-academy-dom' lang="en" className='h-full dark'>
      <body className={`${roboto.className} min-h-full dark:bg-gray-900`}>
        <Providers>
          <NavBar />
          <main className='flex flex-1 flex-col max-w-screen-xl w-full mx-auto '>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
